# Generated by Django 2.2.11 on 2020-04-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_readnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
