# Generated by Django 2.2.11 on 2020-04-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_type',
        ),
        migrations.DeleteModel(
            name='BlogType',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
