# Generated by Django 2.2.11 on 2020-04-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_meat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meat',
        ),
    ]
