# Generated by Django 2.2.11 on 2020-04-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200410_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
